# Generated by Django 5.0 on 2025-10-07 20:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('borough', models.CharField(blank=True, max_length=50, null=True)),
                ('rental_type', models.CharField(choices=[('sublet', 'Sublet'), ('new_lease', 'New Lease'), ('month_to_month', 'Month to Month'), ('short_term', 'Short Term')], max_length=20)),
                ('room_type', models.CharField(choices=[('private_room', 'Private Room'), ('shared_room', 'Shared Room'), ('entire_place', 'Entire Place')], max_length=20)),
                ('price', models.IntegerField()),
                ('date_available', models.DateField()),
                ('furnished', models.CharField(choices=[('fully_furnished', 'Fully Furnished'), ('unfurnished', 'Unfurnished'), ('partially_furnished', 'Partially Furnished')], max_length=30)),
                ('vegan_household', models.CharField(choices=[('fully_vegan', 'Fully Vegan'), ('mixed_household', 'Mixed Household')], max_length=30)),
                ('about_lister', models.TextField()),
                ('lister_relationship', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('tenant', 'Tenant'), ('roommate', 'Roommate')], max_length=30)),
                ('rental_requirements', models.TextField(blank=True, null=True)),
                ('pet_policy', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('include_phone', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('payment_submitted', 'Payment Submitted'), ('active', 'Active'), ('expired', 'Expired'), ('deactivated', 'Deactivated')], default='draft', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
