# Generated by Django 5.0 on 2025-10-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='date_available',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='listing',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
