# Generated by Django 5.2.6 on 2025-10-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_date_available_listing_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='seeking_roommate',
            field=models.BooleanField(default=False),
        ),
    ]
