# Generated by Django 5.2.6 on 2025-10-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_seeking_roommate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='about_lister',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='furnished',
            field=models.CharField(blank=True, choices=[('fully_furnished', 'Fully Furnished'), ('unfurnished', 'Unfurnished'), ('partially_furnished', 'Partially Furnished')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lister_relationship',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('manager', 'Manager'), ('tenant', 'Tenant'), ('roommate', 'Roommate')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rental_type',
            field=models.CharField(blank=True, choices=[('sublet', 'Sublet'), ('new_lease', 'New Lease'), ('month_to_month', 'Month to Month'), ('short_term', 'Short Term')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='room_type',
            field=models.CharField(blank=True, choices=[('private_room', 'Private Room'), ('shared_room', 'Shared Room'), ('entire_place', 'Entire Place')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='vegan_household',
            field=models.CharField(blank=True, choices=[('fully_vegan', 'Fully Vegan'), ('mixed_household', 'Mixed Household')], default='', max_length=30),
        ),
    ]
