# Generated by Django 5.2.6 on 2026-03-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_alter_listing_about_lister_alter_listing_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="neighborhood",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="size",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="transportation",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
