# Generated by Django 5.2.6 on 2025-10-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_about_lister_alter_listing_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price_per_month',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_per_night',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_per_week',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_period',
            field=models.CharField(choices=[('per_night', 'Per Night'), ('per_week', 'Per Week'), ('per_month', 'Per Month'), ('free', 'Free/Trade')], default='per_month', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rental_type',
            field=models.CharField(blank=True, choices=[('sublet', 'Sublet'), ('new_lease', 'New Lease'), ('month_to_month', 'Month to Month'), ('short_term', 'Short Term'), ('house_sit', 'House Sit/Exchange')], default='', max_length=20),
        ),
    ]
