# Generated by Django 5.2.6 on 2025-10-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_price_per_month_listing_price_per_night_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
