# Generated by Django 5.2.6 on 2025-10-14 00:19

from decimal import Decimal
from django.db import migrations


def recalculate_price_conversions(apps, schema_editor):
    """Recalculate price conversions for all existing listings"""
    Listing = apps.get_model('listings', 'Listing')

    # Use string literals directly (can't import PricePeriod in migrations)
    PER_NIGHT = 'per_night'
    PER_WEEK = 'per_week'
    PER_MONTH = 'per_month'
    FREE = 'free'

    for listing in Listing.objects.all():
        if listing.price and listing.price_period != FREE:
            if listing.price_period == PER_NIGHT:
                listing.price_per_night = Decimal(listing.price)
                listing.price_per_week = Decimal(listing.price) * Decimal('7')
                listing.price_per_month = Decimal(listing.price) * Decimal('30')
            elif listing.price_period == PER_WEEK:
                listing.price_per_night = Decimal(listing.price) / Decimal('7')
                listing.price_per_week = Decimal(listing.price)
                listing.price_per_month = Decimal(listing.price) * Decimal('4.33')
            elif listing.price_period == PER_MONTH:
                listing.price_per_night = Decimal(listing.price) / Decimal('30')
                listing.price_per_week = Decimal(listing.price) / Decimal('4.33')
                listing.price_per_month = Decimal(listing.price)
        else:
            # Free listings
            listing.price_per_night = Decimal('0')
            listing.price_per_week = Decimal('0')
            listing.price_per_month = Decimal('0')

        listing.save()


def reverse_func(apps, schema_editor):
    """No need to reverse - conversions can stay"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_price'),
    ]

    operations = [
        migrations.RunPython(recalculate_price_conversions, reverse_func),
    ]
